if (NOT CHAR_TYPE)
    if (WIN32)
        set(CHAR_TYPE UNICODE)
    else()
        set(CHAR_TYPE CHAR)
    endif()
endif()

if (CHAR_TYPE STREQUAL UNICODE)
    message(STATUS "${PROJECT_NAME}: Compiling with wchar_t.")
    add_definitions(-D_UNICODE -DUNICODE)
else()
    message(STATUS "${PROJECT_NAME}: Compiling with char.")
endif()